bare_lab/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main, create_product_entry, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register, login_user, logout_user
from main.views import edit_product, delete_product, add_product_entry_ajax, create_product_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product-entry', create_product_entry, name='create_product_entry'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<uuid:id>', edit_product, name='edit_product'),
    path('delete/<uuid:id>', delete_product, name='delete_product'),
    path('create-ajax', add_product_entry_ajax, name='add_product_entry_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block meta %} {% endblock meta %}
    <link rel="stylesheet" href="{% static 'css/global.css' %}"/>
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
      tailwind.config = {
        theme: {
          extend: {
            fontFamily: {
              poppins: ['Poppins', 'sans-serif'],
              lora: ['Lora', 'serif'],
              recoleta: ['Recoleta', 'sans-serif'],
              brown: ['Brown', 'sans-serif'],
            },
            colors: {
              mainBackground: '#fff7ef',
              primary: '#ff6f61',
              primaryLight: '#f58a7d',
              primaryDark: '#c45449',
              cinderella: '#fcb6b6',
              palePink: '#e9bcb6',
              lightGreen: '#78c9b4',
              limeGreen: '#bcfda4',
              greenYellow: '#cf3',
              base: {
                  white: '#ffffff',
                  black: '#000000',
              },
            },
          },
        },
      }
    </script>
  </head>
  <body>
    {% block content %} {% endblock content %}
  </body>
</html>

templates/navbar.html
<nav class="bg-white border-b-2 border-black fixed top-0 left-0 z-40 w-screen">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <div class="flex items-center">
        <h1 class="text-2xl font-recoleta text-black">Bare Lab</h1>
      </div>
      <div class="hidden md:flex items-center space-x-8">
        {% if user.is_authenticated %}
          <div class="flex space-x-8 items-center">
            <a href="{% url 'main:show_main' %}" class="text-black-800 font-brown transition duration-300 hover:scale-105">Home</a>
            <a href="#" class="text-black-800 font-brown transition duration-300 hover:scale-105">Products</a>
            <a href="#" class="text-black-800 font-brown transition duration-300 hover:scale-105">Categories</a>
            <a href="#" class="text-black-800 font-brown transition duration-300 hover:scale-105">Cart</a>
          </div>
          <span class="text-black-800 font-brown">Welcome, {{ user.username }}</span>
          <a href="{% url 'main:logout' %}" class="text-red-700 font-brown py-1 px-4 transition duration-300 hover:scale-105">
            Logout
          </a>
        {% else %}
          <a href="{% url 'main:login' %}" class="text-blue-700 font-brown py-1 px-4 transition duration-300 hover:scale-105">
            Login
          </a>
          <a href="{% url 'main:register' %}" class="text-lightGreen font-brown py-1 px-4 transition duration-300 hover:scale-105">
            Register
          </a>
        {% endif %}
      </div>
      <div class="md:hidden flex items-center">
        <button class="mobile-menu-button">
          <svg class="w-6 h-6 text-black" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
            <path d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
        </button>
      </div>
    </div>
  </div>
  
  <!-- Mobile menu -->
  <div class="mobile-menu hidden md:hidden px-4 w-full">
    <div class="pt-2 pb-3 space-y-1 mx-auto">
      {% if user.is_authenticated %}
      <a href="#" class="block text-black-800 font-brown py-2">Home</a>
      <a href="#" class="block text-black-800 font-brown py-2">Products</a>
      <a href="#" class="block text-black-800 font-brown py-2">Categories</a>
      <a href="#" class="block text-black-800 font-brown py-2">Cart</a>
      <span class="block text-black-800 font-brown px-3 py-2">Welcome, {{ user.username }}</span>
      <a href="{% url 'main:logout' %}" class="block text-center font-brown bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded transition duration-300">
        Logout
      </a>
      {% else %}
        <a href="{% url 'main:login' %}" class="block font-brown text-center bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded transition duration-300 mb-2">
          Login
        </a>
        <a href="{% url 'main:register' %}" class="block font-brown text-center bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded transition duration-300">
          Register
        </a>
      {% endif %}
    </div>
  </div>
  
  <script>
    const btn = document.querySelector("button.mobile-menu-button");
    const menu = document.querySelector(".mobile-menu");
    
    btn.addEventListener("click", () => {
      menu.classList.toggle("hidden");
    });
  </script>
</nav>