bare_lab/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main, create_product_entry, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register, login_user, logout_user
from main.views import edit_product, delete_product, add_product_entry_ajax, create_product_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product-entry', create_product_entry, name='create_product_entry'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<uuid:id>', edit_product, name='edit_product'),
    path('delete/<uuid:id>', delete_product, name='delete_product'),
    path('create-ajax', add_product_entry_ajax, name='add_product_entry_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

main/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Product (models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200)
    price = models.IntegerField()
    description = models.TextField()
    stock = models.IntegerField()
    category = models.CharField(max_length=100)
    rating = models.IntegerField()

main/forms.py
from django.forms import ModelForm
from main.models import Product
from django.utils.html import strip_tags

class ProductEntryForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description", "stock", "category", "rating"]

    def clean_name(self):
        name = self.cleaned_data["name"]
        return strip_tags(name)

    def clean_description(self):
        description = self.cleaned_data["description"]
        return strip_tags(description)
    
    def clean_category(self):
        category = self.cleaned_data["category"]
        return strip_tags(category)

main/views.py
from django.shortcuts import render, redirect
from main.forms import ProductEntryForm
from main.models import Product
from django.http import HttpResponse
from django.core import serializers

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse

from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.html import strip_tags

from django.views.decorators.csrf import csrf_exempt
import json
from django.http import JsonResponse

# Create your views here.
@login_required(login_url='/login')
def show_main(request):

    context = {
        'name' : request.user.username,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_product_entry(request):
    form = ProductEntryForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return redirect('main:show_main')

    context = {'form': form}
    return render(request, "create_product_entry.html", context)

def show_xml(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
   if request.method == 'POST':
      form = AuthenticationForm(data=request.POST)

      if form.is_valid():
        user = form.get_user()
        login(request, user)
        response = HttpResponseRedirect(reverse("main:show_main"))
        response.set_cookie('last_login', str(datetime.datetime.now()))
        return response
      else:
        messages.error(request, "Invalid username or password. Please try again.")
        
   else:
      form = AuthenticationForm(request)
   context = {'form': form}
   return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_product(request, id):
    # Get product entry berdasarkan id
    product = Product.objects.get(pk = id)

    # Set product entry  sebagai instance dari form
    form = ProductEntryForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    # Get product berdasarkan id
    product = Product.objects.get(pk = id)
    # Hapus product
    product.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
@require_POST
def add_product_entry_ajax(request):
    name = strip_tags(request.POST.get("name"))
    price = request.POST.get("price")
    description = strip_tags(request.POST.get("description"))
    stock = request.POST.get("productStock")
    category = strip_tags(request.POST.get("category"))
    rating = request.POST.get("productRating")
    user = request.user

    new_product = Product(
        name=name, price=price,
        description=description,
        stock=stock, category=category,
        rating=rating, user=user,
    )
    new_product.save()

    return HttpResponse(b"CREATED", status=201)

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)
        new_product = Product.objects.create(
            user=request.user,
            name=data["name"],
            price=int(data["price"]),
            description=data["description"],
            stock=int(data["stock"]),
            category=data["category"],
            rating=int(data["rating"]),
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_product_entry.html
{% extends 'base.html' %} 
{% block content %}
<h1>Add New Product Entry</h1>

<form method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
    <tr>
      <td></td>
      <td>
        <input type="submit" value="Add Product Entry" />
      </td>
    </tr>
  </table>
</form>

{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Edit Product</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="flex flex-col min-h-screen bg-mainBackground">
  <div class="container mx-auto px-12 py-12 mt-16 max-w-xl">
    <h1 class="text-5xl text-center mb-8 font-recoleta">Edit Product</h1>

    <div class="bg-white rounded-lg p-8 shadow-md">
      <form method="POST" class="space-y-3">
        {% csrf_token %}
        {% for field in form %}
          <div class="flex flex-col">
            <label for="{{ field.id_for_label }}" class="mb-1 font-brown text-sm text-gray-700">
              {{ field.label }}
            </label>
            <div class="w-full">
              {% if field.name == 'description' %}
                <textarea 
                  name="{{ field.name }}" 
                  id="{{ field.id_for_label }}" 
                  class="appearance-none block w-full px-4 py-3 border border-gray-300 placeholder-gray-400 text-gray-900 font-brown focus:outline-none focus:ring-primary focus:border-primary focus:z-10 text-sm sm:text-lg"
                  placeholder="{{ field.label }}"
                  rows="4">{{ field.value|default:'' }}</textarea>
              {% else %}
                <input 
                  type="{% if field.name in 'name category' %}text{% else %}number{% endif %}" 
                  name="{{ field.name }}" 
                  id="{{ field.id_for_label }}" 
                  value="{{ field.value|default:'' }}" 
                  class="appearance-none block w-full px-4 py-3 border border-gray-300 placeholder-gray-400 text-gray-900 font-brown focus:outline-none focus:ring-primary focus:border-primary focus:z-10 text-sm sm:text-lg"
                  placeholder="{{ field.label }}"
                />
              {% endif %}
            </div>
            {% if field.help_text %}
              <p class="mt-1 font-brown text-sm text-gray-500">{{ field.help_text }}</p>
            {% endif %}
            {% for error in field.errors %}
              <p class="mt-1 font-brown text-sm text-red-600">{{ error }}</p>
            {% endfor %}
          </div>
        {% endfor %}
        
        <div class="flex justify-center">
          <button type="submit" class="group relative mt-6 w-full flex justify-center py-2 px-3 border border-transparent font-brown rounded-md text-white text-sm tracking-wider sm:text-lg bg-primary shadow-[0px_5px_0px_0px_#c45449] focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-white transition-all duration-950 ease-in-out hover:shadow-none">
            EDIT PRODUCT
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

main/templates/hero_section.html
{% extends 'base.html' %}

{% block meta %}
<title>Bare Lab</title>
{% endblock meta %}

{% block content %}
<header class="relative w-full h-screen bg-cover bg-center" style="background-image: url('https://www.base.co.id/_next/image?url=https%3A%2F%2Fstorage.googleapis.com%2Fbase-lp-assets%2Foutput.lin.jpg&w=1920&q=100');">
    <div class="absolute inset-0 bg-black opacity-50"></div>
    <div class="flex items-center justify-center h-full relative z-10">
        <div class="text-center text-white px-10 pt-20">
            <h1 class="text-5xl sm:text-6xl font-recoleta mb-4">Empower Your Beauty</h1>
            <p class="text-md sm:text-xl font-brown mb-6">Discover the beauty that lies within you and enhance it with our curated products.</p>
        </div>
    </div>
</header>
{% endblock content %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<div class="min-h-screen flex items-center justify-center w-screen bg-mainBackground py-12 px-16">
  <div class="max-w-xl w-full space-y-8">
    <div>
      <h2 class="mt-6 text-center text-black text-4xl sm:text-5xl font-recoleta">
        Hi there, welcome back!
      </h2>
    </div>
    <form class="mt-8 space-y-4" method="POST" action="">
      {% csrf_token %}
      <input type="hidden" name="remember" value="true">
      <div class="">
        <label for="username" class="sr-only">Username</label>
        <input id="username" name="username" type="text" required class="appearance-none rounded-none relative block w-full px-4 py-3 border border-gray-300 placeholder-gray-400 text-gray-900 font-brown focus:outline-none focus:ring-primary focus:border-primary focus:z-10 text-sm sm:text-lg shadow-[0px_0px_20px_4px_#00000010]" placeholder="Username">
      </div>
      <div>
        <label for="password" class="sr-only">Password</label>
        <input id="password" name="password" type="password" required class="appearance-none rounded-none relative block w-full px-4 py-3 border border-gray-300 placeholder-gray-400 text-gray-900 font-brown focus:outline-none focus:ring-primary focus:border-primary focus:z-10 text-sm sm:text-lg shadow-[0px_0px_20px_4px_#00000010]" placeholder="Password">
      </div>

      <div>
        <button type="submit" class="group relative w-full flex justify-center py-2 px-3 border border-transparent font-brown rounded-md text-white text-sm tracking-wider sm:text-lg bg-primary hover:bg-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-white hover:text-primary transition-all duration-300 ease-in-out">
          SIGN IN
        </button>
      </div>
    </form>

    {% if messages %}
    <div class="mt-4">
      {% for message in messages %}
      {% if message.tags == "success" %}
            <div class="bg-green-100 border border-green-400 text-green-700 font-brown px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% elif message.tags == "error" %}
            <div class="bg-red-100 border border-red-400 text-red-700 font-brown  py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% else %}
            <div class="bg-blue-100 border border-blue-400 text-blue-700 font-brown py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% endif %}
      {% endfor %}
    </div>
    {% endif %}

    <div class="text-sm sm:text-lg text-center mt-4">
      <p class="text-black font-brown">
        Don't have an account?
        <a href="{% url 'main:register' %}" class="font-medium text-primary hover:text-cinderella">
          Sign up here
        </a>
      </p>
    </div>
  </div>
</div>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Bare Lab</title>
<script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="overflow-x-hidden min-h-screen bg-white flex flex-col">
  {% include "hero_section.html" %}
  <div class="px-16 py-5 mb-20">
    <div class="mt-1 py-8 sm:px-0 sm:mb-10 flex justify-end">
        <a href="{% url 'main:create_product_entry' %}" class="text-center bg-primary text-white font-bold font-brown mr-6 py-3 px-8 border border-transparent hover:bg-white hover:text-primary hover:border-primary duration-300 ease-in-out">
            Add New Product
        </a>
        <button data-modal-target="crudModal" data-modal-toggle="crudModal" class="btn bg-primary text-center text-white font-bold border border-transparent hover:bg-white hover:text-primary hover:border-primary py-3 px-8 transition duration-300 ease-in-out" onclick="showModal();">
          Add New Product by AJAX
        </button>
    </div>
    <div id="product_entry_cards"></div>
  </div>
</div>

<div id="crudModal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-50 w-full flex items-center justify-center bg-gray-800 bg-opacity-50 overflow-x-hidden overflow-y-hidden transition-opacity duration-300 ease-out">
  <div id="crudModalContent" class="relative bg-white rounded-lg shadow-lg w-5/6 sm:w-3/4 md:w-1/2 lg:w-1/3 mx-4 sm:mx-0 max-h-[90vh] overflow-y-auto transform scale-95 opacity-0 transition-transform transition-opacity duration-300 ease-out">
    
    <!-- Modal header -->
    <div class="flex items-center justify-between p-4 border-b rounded-t">
      <h3 class="text-xl font-brown font-bold text-gray-900">
        Add New Product
      </h3>
      <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" id="closeModalBtn">
        <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
        </svg>
        <span class="sr-only">Close modal</span>
      </button>
    </div>

    <!-- Modal body -->
    <div class="px-6 py-4 space-y-6 form-style">
      <form id="productEntryForm">
        <div class="mb-4">
          <label for="name" class="block text-sm font-brown text-gray-700">Name</label>
          <input type="text" id="name" name="name" class="mt-1 block w-full border border-gray-300 p-2 font-brown focus:outline-none focus:ring-primary focus:border-primary focus:z-10" placeholder="Name" required>
          <p id="nameError" class="text-red-500 font-brown text-xs mt-1 hidden">Name field cannot be blank or contain HTML tags.</p>
        </div>

        <div class="mb-4">
          <label for="price" class="block text-sm font-brown text-gray-700">Price</label>
          <input type="number" id="price" name="price" min="1" max="1000000" class="mt-1 block w-full border border-gray-300 p-2 focus:outline-none focus:ring-primary focus:border-primary focus:z-10 font-brown" placeholder="Price" required>
        </div>

        <div class="mb-4">
          <label for="description" class="block text-sm font-brown text-gray-700">Description</label>
          <textarea id="description" name="description" rows="3" class="mt-1 block w-full h-52 resize-none border border-gray-300 p-2 font-brown focus:outline-none focus:ring-primary focus:border-primary focus:z-10" placeholder="Description" required></textarea>
          <p id="descError" class="text-red-500 font-brown text-xs mt-1 hidden">Description field cannot be blank or contain HTML tags.</p>

        </div>

        <div class="mb-4">
          <label for="productStock" class="block text-sm font-brown text-gray-700">Stock</label>
          <input type="number" id="productStock" name="productStock" min="1" max="250" class="mt-1 block w-full border border-gray-300 p-2 font-brown focus:outline-none focus:ring-primary focus:border-primary focus:z-10" placeholder="Stock" required>
        </div>

        <div class="mb-4">
          <label for="category" class="block text-sm font-brown text-gray-700">Category</label>
          <input type="text" id="category" name="category" class="mt-1 block w-full border border-gray-300 p-2 font-brown focus:outline-none focus:ring-primary focus:border-primary focus:z-10" placeholder="Category" required>
          <p id="categoryError" class="text-red-500 font-brown text-xs mt-1 hidden">Category field cannot be blank or contain HTML tags.</p>
        </div>

        <div class="mb-4">
          <label for="productRating" class="block text-sm font-brown text-gray-700">Rating</label>
          <input type="number" id="productRating" name="productRating" min="1" max="5" class="mt-1 block w-full border border-gray-300 p-2 font-brown focus:outline-none focus:ring-primary focus:border-primary focus:z-10" placeholder="Rating" required>
        </div>
      </form>
    </div>

    <!-- Modal footer -->
    <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2 p-6 border-t border-gray-200 rounded-b justify-center md:justify-end">
      <button type="button" class="bg-gray-400 hover:bg-gray-500 text-white font-brown py-2 px-4" id="cancelButton">Cancel</button>
      <button type="submit" id="submitProductEntry" form="productEntryForm" class="bg-primary hover:bg-primaryDark text-white font-brown py-2 px-4">Save</button>
    </div>
  </div>
</div>

<script>
  async function getProductEntries(){
      return fetch("{% url 'main:show_json' %}").then((res) => res.json())
  }

  async function refreshProductEntries() {
    document.getElementById("product_entry_cards").innerHTML = "";
    document.getElementById("product_entry_cards").className = "";
    const productEntries = await getProductEntries();
    let htmlString = "";
    let classNameString = "";

    if (productEntries.length === 0) {
        classNameString = "flex flex-col items-center justify-center min-h-[24rem] p-6";
        htmlString = `
            <div class="flex flex-col items-center justify-center min-h-[24rem] p-6">
                <img src="{% static 'image/no-product.png' %}" alt="Sad face" class="w-32 h-32 mb-4"/>
                <p class="text-center text-gray-600 mt-4">Belum ada data produk.</p>
            </div>
        `;
    } else {
        classNameString = "columns-1 sm:columns-2 lg:columns-3 gap-12 space-y-6 w-full";
        productEntries.forEach((item) => {
            const name = DOMPurify.sanitize(item.fields.name);
            const description = DOMPurify.sanitize(item.fields.description);
            const category= DOMPurify.sanitize(item.fields.category);
            let starsHtml = "";

            // Generate stars based on the rating
            for (let i = 1; i <= 5; i++) {
                if (i <= item.fields.rating) {
                    starsHtml += `
                        <svg class="w-5 h-5 text-yellow-400" fill="currentColor" viewBox="0 0 20 20">
                            <path d="M10 15.27L16.18 19l-1.64-7.03L20 7.24l-7.19-.61L10 0 7.19 6.63 0 7.24l5.46 4.73L3.82 19z"></path>
                        </svg>
                    `;
                } else {
                    starsHtml += `
                        <svg class="w-5 h-5 text-gray-300" fill="currentColor" viewBox="0 0 20 20">
                            <path d="M10 15.27L16.18 19l-1.64-7.03L20 7.24l-7.19-.61L10 0 7.19 6.63 0 7.24l5.46 4.73L3.82 19z"></path>
                        </svg>
                    `;
                }
            }

            htmlString += `
            <div class="relative break-inside-avoid">
              <div class="relative bg-white mb-6 flex flex-col">
                <div class="bg-cinderella text-gray-800 p-4"></div>
                <div class="p-4 flex-grow">
                  <p class="font-brown text-sm text-gray-500 mb-2">${category}</p>
                  <p class="font-brown font-bold text-xl mb-2">${name}</p>
                  <p class="text-gray-700 mb-2 font-brown">
                    <span class="bg-[linear-gradient(to_bottom,transparent_0%,transparent_calc(100%_-_1px),#E5D9FF_calc(100%_-_1px))] bg-[length:100%_1.5rem] pb-1">${description}</span>
                  </p>
                  <div class="mt-4">
                    <div class="flex items-center mb-2">
                      ${starsHtml} <!-- Insert the generated stars HTML -->
                    </div>
                    <p class="text-gray-700 font-brown font-bold">Rp ${item.fields.price}</p>
                  </div>
                </div>
                <div class="flex justify-between">
                  <a href="/edit-product/${item.pk}" class="text-center bg-white border border-black text-black hover:bg-lightGreen hover:text-white hover:border-transparent p-2 transition duration-300 ease-in-out flex-1 mr-2">
                    Edit
                  </a>
                  <a href="/delete/${item.pk}" class="text-center bg-white border border-black text-black hover:bg-primaryDark hover:text-white hover:border-transparent p-2 transition duration-300 ease-in-out flex-1 ml-2">
                    Delete
                  </a>
                </div>
              </div>
            </div>
            `;
        });
    }
    document.getElementById("product_entry_cards").className = classNameString;
    document.getElementById("product_entry_cards").innerHTML = htmlString;
}
refreshProductEntries();

  const modal = document.getElementById('crudModal');
  const modalContent = document.getElementById('crudModalContent');

  function showModal() {
      const modal = document.getElementById('crudModal');
      const modalContent = document.getElementById('crudModalContent');

      modal.classList.remove('hidden'); 
      setTimeout(() => {
        modalContent.classList.remove('opacity-0', 'scale-95');
        modalContent.classList.add('opacity-100', 'scale-100');
      }, 50); 
  }

  function hideModal() {
      const modal = document.getElementById('crudModal');
      const modalContent = document.getElementById('crudModalContent');

      modalContent.classList.remove('opacity-100', 'scale-100');
      modalContent.classList.add('opacity-0', 'scale-95');

      setTimeout(() => {
        modal.classList.add('hidden');
      }, 150); 
  }

  document.getElementById("cancelButton").addEventListener("click", hideModal);
  document.getElementById("closeModalBtn").addEventListener("click", hideModal);

  function addProductEntry() {
    const name = document.getElementById("name").value;
    const description = document.getElementById("description").value;
    const category= document.getElementById("category").value;
    const nameError = document.getElementById("nameError");
    const descError = document.getElementById("descError");
    const categoryError = document.getElementById("categoryError");

    if (!name.trim() || /<[^>]*>/.test(name)) {
        nameError.classList.remove("hidden");
        return false;
    }
    if (!description.trim() || /<[^>]*>/.test(description)) {
        descError.classList.remove("hidden");
        return false;
    }
    if (!category.trim() || /<[^>]*>/.test(category)) {
        categoryError.classList.remove("hidden");
        return false;
    }

    fetch("{% url 'main:add_product_entry_ajax' %}", {
      method: "POST",
      body: new FormData(document.querySelector('#productEntryForm')),
    })
    .then(response => refreshProductEntries())

    document.getElementById("productEntryForm").reset();
    hideModal();
    return false;
  }

  document.getElementById("productEntryForm").addEventListener("submit", (e) => {
    e.preventDefault();
    addProductEntry();
  })

</script>
{% endblock content %}

main/templates/product_card.html
<div class="relative break-inside-avoid">
    <div class="relative bg-white mb-6 flex flex-col">
        <div class="bg-primary text-gray-800 p-4">
        </div>
        <div class="p-4 flex-grow">
            <p class="font-brown text-sm text-gray-500 mb-2">{{ product_entry.category }}</p>
            <p class="font-brown font-bold text-xl mb-2">{{ product_entry.name }}</p>
            <p class="text-gray-700 mb-2 font-brown">
                <span class="bg-[linear-gradient(to_bottom,transparent_0%,transparent_calc(100%_-_1px),#E5D9FF_calc(100%_-_1px))] bg-[length:100%_1.5rem] pb-1">{{ product_entry.description }}</span>
            </p>
            <div class="mt-4">
                <div class="flex items-center mb-2">
                    {% for i in '12345'|make_list %}
                        {% if forloop.counter <= product_entry.rating %}
                            <svg class="w-5 h-5 text-yellow-400" fill="currentColor" viewBox="0 0 20 20">
                                <path d="M10 15.27L16.18 19l-1.64-7.03L20 7.24l-7.19-.61L10 0 7.19 6.63 0 7.24l5.46 4.73L3.82 19z"/>
                            </svg>
                        {% else %}
                            <svg class="w-5 h-5 text-gray-300" fill="currentColor" viewBox="0 0 20 20">
                                <path d="M10 15.27L16.18 19l-1.64-7.03L20 7.24l-7.19-.61L10 0 7.19 6.63 0 7.24l5.46 4.73L3.82 19z"/>
                            </svg>
                        {% endif %}
                    {% endfor %}
                </div>
                <p class="text-gray-700 font-brown font-bold">Rp {{ product_entry.price }}</p>
            </div>
        </div>
        <div class="flex justify-between">
            <a href="{% url 'main:edit_product' product_entry.pk %}" class="text-center bg-white border border-black text-black hover:bg-lightGreen hover:text-white hover:border-transparent p-2 transition duration-300 ease-in-out flex-1 mr-2">
                Edit
            </a>
            <a href="{% url 'main:delete_product' product_entry.pk %}" class="text-center bg-white border border-black text-black hover:bg-primaryDark hover:text-white hover:border-transparent p-2 transition duration-300 ease-in-out flex-1 ml-2">
                Delete
            </a>
        </div>
    </div>
</div>

main/templates/tes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Judul</h1>
    <h2>Subjudul</h2>
    <p>Deskripsi singkat</p>
    <thead>
        <tr>
            <th>Nama</th>
            <th>NPM</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Claudia</td>
            <td>12345678</td>
        </tr>
    </tbody>
</body>
</html>